# æ¬¢è¿ä½¿ç”¨ âš¡ï¸serverlessâš¡ï¸ ç»„ä»¶
#
# serverlessç»„ä»¶æ˜¯åŸºäºå…·ä½“ä½¿ç”¨åœºæ™¯(Express, é™æ€ç½‘ç«™ç­‰)æä¾›çš„å®šåˆ¶äº‘èµ„æºç¼–æ’å’Œç»„ç»‡çš„è§£å†³æ–¹æ¡ˆã€‚
# è¿™æ˜¯serverlessçš„ä¸»è¦é…ç½®æ–‡ä»¶ï¼ŒåŒ…å«äº†ä¸€äº›ä½¿ç”¨ç¤ºä¾‹ä»¥åŠæ³¨é‡Šè¯´æ˜ã€‚
# æ‚¨åªéœ€å‡ è¡Œé…ç½®æè¿°ï¼Œå³å¯è¿›è¡Œäº‘å‡½æ•°ã€API ç½‘å…³ã€COSã€DB ç­‰
# Serverless èµ„æºè¿›è¡Œå¿«é€Ÿåˆ›å»ºã€éƒ¨ç½²å’Œä¿®æ”¹ã€‚
#
# æœ‰å…³å®Œæ•´çš„é…ç½®é€‰é¡¹ï¼Œè¯·æ£€æŸ¥æ–‡æ¡£ï¼š
# https://cloud.tencent.com/document/product/1154/51080
#
# ğŸ‘©â€ğŸ’» Happy Coding ğŸ‘¨â€ğŸ’»

# ##åº”ç”¨ä¿¡æ¯##
app: helloworld # appåç§°(appå”¯ä¸€è¯†åˆ«æ ‡è¯†)ã€‚åŒè´¦å·ä¸‹éœ€å”¯ä¸€ï¼Œç•™ç©ºåˆ™ç»§æ‰¿ç»„ä»¶å®ä¾‹åç§°
component: scf # [å¿…é€‰]è¦ä½¿ç”¨ç»„ä»¶ï¼Œæ›´å¤šç»„ä»¶è¯·æŸ¥çœ‹ https://github.com/serverless-components
name: scf-nodejs # [å¿…é€‰]ç»„ä»¶å®ä¾‹åç§°

# ##scf ç»„ä»¶é…ç½®##
# æ›´å¤šå†…å®¹è¯·æŸ¥çœ‹: https://github.com/serverless-components/tencent-scf/blob/master/docs/configure.md
inputs:
  src: ./ # æ‰§è¡Œç›®å½•
  handler: index.main_handler # å‡½æ•°æ–¹æ³•åç§°ã€æ–‡ä»¶åç§°.å‡½æ•°åç§°ã€‘ã€‚åç§°è¦æ±‚å­—æ¯å¼€å§‹å’Œç»“å°¾ï¼Œå…è®¸ä½¿ç”¨æ•°å­—ã€ä¸‹åˆ’çº¿(_)å’Œè¿æ¥ç¬¦(-)ï¼Œ2-60 ä¸ªå­—ç¬¦ã€‚
  region: ap-guangzhou # éƒ¨ç½²ç›®æ ‡åœ°åŒºã€‚ æ›´å¤šå‚è€ƒ https://cloud.tencent.com/document/api/583/17238#.E5.9C.B0.E5.9F.9F.E5.88.97.E8.A1.A8
  runtime: Nodejs10.15 # è¿è¡Œç¯å¢ƒã€‚[Nodejs10.15, Nodejs12.16]
  memorySize: 128 # å‡½æ•°è¿è¡Œå†…å­˜ï¼Œå•ä½MBã€‚[64, 128, ... 3072]ï¼Œä»¥ 128 é€’å¢
  timeout: 3 # å‡½æ•°è¶…æ—¶æ—¶é—´ï¼Œå•ä½ç§’ï¼ŒèŒƒå›´ 1-900
  events: # è§¦å‘å™¨
    - apigw: # apiç½‘å…³è§¦å‘å™¨ï¼Œå·²æœ‰apigwæœåŠ¡ï¼Œé…ç½®è§¦å‘å™¨
        parameters:
          endpoints:
            - path: /
              method: GET
