app: ocr-app
name: ocr-bucket
component: cos

inputs:
  bucket: ocr-bucket
  region: ap-guangzhou
  protocol: https
  acl:
    permissions: public-read
  cors:
    - maxAgeSeconds: '0'
      allowedMethods:
        - GET
        - PUT
        - POST
      allowedOrigins: '*'
      allowedHeaders: '*'
