app: ocr-app
component: website
name: ocr-frontend

inputs:
  region: ${output:${stage}:${app}:ocr-bucket.region}
  bucketName: ocr-app
  protocol: https
  src:
    src: ./
    hook: npm run build
    dist: ./build
    envPath: ./
    index: index.html
    error: index.html
  env:
    # get api url after below api service deployed.
    apiUrl: ${output:${stage}:${app}:ocr-backend.apigw.url}
