app: ocr-app
component: express
name: ocr-backend

inputs:
  src: ./
  functionName: ${name}
  region: ${output:${stage}:${app}:ocr-bucket.region}
  runtime: Nodejs10.15
  functionConf:
    timeout: 10
    environment:
      variables:
        REGION: ${output:${stage}:${app}:ocr-bucket.region}
        TENCENT_APP_ID: ${env:TENCENT_APP_ID}
        TENCENT_SECRET_ID: ${env:TENCENT_SECRET_ID}
        TENCENT_SECRET_KEY: ${env:TENCENT_SECRET_KEY}
        BUCKET: ${output:${stage}:${app}:ocr-bucket.bucket}
  apigatewayConf:
    enableCORS: true
    protocols:
      - http
      - https
