name: restful-api
author: Tencent Cloud, Inc.
org: Tencent Cloud, Inc.
description:
  Build a serverless REST API application with tencent serverless SCF component,
  support GET/PUT methods.
keywords: tencent, serverless, rest api, scf
repo: https://github.com/serverless-components/tencent-examples/tree/master/restful-api
readme: https://github.com/serverless-components/tencent-examples/tree/master/restful-api/README.md
license: MIT
src:
  src: ./src
  exclude:
    - .env
    - '.git/**'
