# æ¬¢è¿ä½¿ç”¨ âš¡ï¸serverlessâš¡ï¸ ç»„ä»¶
#
# serverlessç»„ä»¶æ˜¯åŸºäºå…·ä½“ä½¿ç”¨åœºæ™¯(Express, é™æ€ç½‘ç«™ç­‰)æä¾›çš„å®šåˆ¶äº‘èµ„æºç¼–æ’å’Œç»„ç»‡çš„è§£å†³æ–¹æ¡ˆã€‚
# è¿™æ˜¯serverlessçš„ä¸»è¦é…ç½®æ–‡ä»¶ï¼ŒåŒ…å«äº†ä¸€äº›ä½¿ç”¨ç¤ºä¾‹ä»¥åŠæ³¨é‡Šè¯´æ˜ã€‚
# æ‚¨åªéœ€å‡ è¡Œé…ç½®æè¿°ï¼Œå³å¯è¿›è¡Œäº‘å‡½æ•°ã€API ç½‘å…³ã€COSã€DB ç­‰
# Serverless èµ„æºè¿›è¡Œå¿«é€Ÿåˆ›å»ºã€éƒ¨ç½²å’Œä¿®æ”¹ã€‚
#
# æœ‰å…³å®Œæ•´çš„é…ç½®é€‰é¡¹ï¼Œè¯·æ£€æŸ¥æ–‡æ¡£ï¼š
# https://cloud.tencent.com/document/product/1154/51080
#
# ğŸ‘©â€ğŸ’» Happy Coding ğŸ‘¨â€ğŸ’»

# ##åº”ç”¨ä¿¡æ¯##
app: appDemo # appåç§°(appå”¯ä¸€è¯†åˆ«æ ‡è¯†)ã€‚åŒè´¦å·ä¸‹éœ€å”¯ä¸€ï¼Œç•™ç©ºåˆ™ç»§æ‰¿ç»„ä»¶å®ä¾‹åç§°
component: express # [å¿…é€‰]è¦ä½¿ç”¨ç»„ä»¶ï¼Œæ›´å¤šç»„ä»¶è¯·æŸ¥çœ‹ https://github.com/serverless-components
name: expressDemo # [å¿…é€‰]ç»„ä»¶å®ä¾‹åç§°

# ##express ç»„ä»¶é…ç½®##
# æ›´å¤šé…ç½®è¯·æŸ¥çœ‹ï¼šhttps://github.com/serverless-components/tencent-express/blob/master/docs/configure.md
inputs:
  src: ./ # æ‰§è¡Œç›®å½•
    src: ./
    exclude:
      - .env
  region: ap-guangzhou # éƒ¨ç½²ç›®æ ‡åœ°åŒºã€‚ æ›´å¤šå‚è€ƒ https://cloud.tencent.com/document/api/583/17238#.E5.9C.B0.E5.9F.9F.E5.88.97.E8.A1.A8
  runtime: Nodejs10.15 # è¿è¡Œç¯å¢ƒã€‚[Nodejs10.15, Nodejs12.16]
  apigatewayConf: # API ç½‘å…³
    protocols:
      - http
      - https
    environment: release # å‘å¸ƒç¯å¢ƒã€‚[test, prepubï¼Œrelease]
=======
# ä½¿ç”¨æ„‰å¿«

# ##åº”ç”¨ä¿¡æ¯## 
app: express-app # appåº”ç”¨åç§°(åŒè´¦å·ä¸‹åº”ç”¨åç§°å”¯ä¸€)ã€‚ç•™ç©ºåˆ™å–å½“å‰ç»„ä»¶çš„å®ä¾‹åç§°ã€‚
component: express # [å¿…é€‰]ä½¿ç”¨ç»„ä»¶çš„åç§°ï¼Œæ›´å¤šåœ¨ https://github.com/serverless-components
name: expressDemo # [å¿…é€‰]ç»„ä»¶çš„å®ä¾‹åç§°ã€‚
# stage: dev # ç¯å¢ƒåç§°ã€‚é»˜è®¤å€¼æ˜¯ devã€‚å¯ä½¿ç”¨ ${env.STAGE} é€šè¿‡ç¯å¢ƒå˜é‡å®šä¹‰ã€‚

# ##Express ç»„ä»¶é…ç½®##
# æ›´å¤šå†…å®¹è¯·æŸ¥çœ‹ï¼šhttps://github.com/serverless-components/tencent-express/blob/master/docs/configure.md
inputs:
  runtime: Nodejs10.15 # è¿è¡Œæ—¶ç¯å¢ƒã€‚ [Nodejs10.15, Nodejs12.16]
  region: ap-guangzhou # äº‘å‡½æ•°æ‰€åœ¨åŒºåŸŸã€‚ [ap-hangzhou,ap-shanghai,ap-beijing,ap-chengdu,ap-hongkong]
  src: # é¡¹ç›®ä»£ç è·¯å¾„
    src: ./ # æœ¬åœ°éœ€è¦æ‰“åŒ…çš„æ–‡ä»¶ç›®å½•
    exclude: # è¢«æ’é™¤çš„æ–‡ä»¶æˆ–ç›®å½•
      - .env
      - .git
  apigatewayConf: # apiç½‘å…³é…ç½®
    enableCORS: false # æ˜¯å¦å…è®¸è·¨åŸŸ
    protocols: # å¼€é€šåè®®
      - http
      - https
    environment: release # ç¯å¢ƒå˜é‡
    # customDomains: # è‡ªå®šä¹‰åŸŸåç»‘å®š
    #   - domain: foobar.com # å¾…ç»‘å®šçš„è‡ªå®šä¹‰çš„åŸŸå
    #     certificateId: foobar # å¾…ç»‘å®šè‡ªå®šä¹‰åŸŸåçš„è¯ä¹¦ID
    #     protocols: # ç»‘å®šè‡ªå®šä¹‰åŸŸåçš„åè®®ç±»å‹ã€‚
    #       - http
    #       - https
