name: ocr-app
author: Tencent Cloud, Inc.
description: Deploy a serverless OCR application.
keywords: tencent, serverless, express, website, ocr
repo: https://github.com/serverless-components/tencent-examples/tree/master/ocr-app
readme: https://github.com/serverless-components/tencent-examples/tree/master/ocr-app/README.md
license: MIT
src:
  src: ./
  exclude:
    - .env
    - '.git/**'
    - serverless.yml
    - '**/node_modules'
    - '**/package-lock.json'
