# æ¬¢è¿ä½¿ç”¨ serverless ç»„ä»¶
#
# serverlessç»„ä»¶æ˜¯åŸºäºå…·ä½“ä½¿ç”¨åœºæ™¯(Express, é™æ€ç½‘ç«™)æä¾›çš„å®šåˆ¶äº‘èµ„æºç¼–æ’å’Œç»„ç»‡çš„è§£å†³æ–¹æ¡ˆã€‚
# è¿™æ˜¯serverlessçš„ä¸»è¦é…ç½®æ–‡ä»¶ï¼ŒåŒ…å«äº†ä¸€äº›ä½¿ç”¨ç¤ºä¾‹ä»¥åŠæ³¨é‡Šè¯´æ˜ã€‚
# æ‚¨åªéœ€å‡ è¡Œé…ç½®æè¿°ï¼Œå³å¯è¿›è¡Œäº‘å‡½æ•°ã€API ç½‘å…³ã€COSã€DB ç­‰
# Serverless èµ„æºçš„å¿«é€Ÿåˆ›å»ºã€éƒ¨ç½²å’Œä¿®æ”¹ã€‚
#
# æœ‰å…³å®Œæ•´çš„é…ç½®é€‰é¡¹ï¼Œè¯·æ£€æŸ¥æ–‡æ¡£ï¼š
# https://cloud.tencent.com/document/product/1154/51080
#
# ä½¿ç”¨æ„‰å¿« âš¡ï¸ğŸš€

# ##åº”ç”¨ä¿¡æ¯##
component: egg # [å¿…é€‰]ä½¿ç”¨ç»„ä»¶çš„åç§°ï¼Œæ›´å¤šåœ¨ https://github.com/serverless-components
name: egg # [å¿…é€‰]ç»„ä»¶çš„å®ä¾‹åç§°
app: appDemo # appåº”ç”¨åç§°(åŒè´¦å·ä¸‹åº”ç”¨åç§°å”¯ä¸€)ã€‚ç•™ç©ºåˆ™å–å½“å‰ç»„ä»¶çš„å®ä¾‹åç§°ã€‚

# ##egg ç»„ä»¶é…ç½®##
# æ›´å¤šå†…å®¹è¯·æŸ¥çœ‹ï¼šhttps://github.com/serverless-components/tencent-egg/blob/master/docs/configure.md
inputs:
  src: ./ # é»˜è®¤ä¸ºå½“å‰ç›®å½•, å¦‚æœæ˜¯å¯¹è±¡, é…ç½®å‚æ•°å‚è€ƒ æ‰§è¡Œç›®å½•
  region: ap-guangzhou # é¡¹ç›®éƒ¨ç½²æ‰€åœ¨åŒºåŸŸï¼Œé»˜è®¤å¹¿å·åŒº
  runtime: Nodejs10.15 # æ‰§è¡Œç¯å¢ƒ, ç›®å‰æ”¯æŒ: Nodejs6.10, Nodejs8.9, Nodejs10.15, Nodejs12.16
  role: SCF_QcsRole # è§’è‰²æƒé™
  apigatewayConf: #  apiç½‘å…³é…ç½®
    protocols: # å‰ç«¯è¯·æ±‚çš„ç±»å‹ï¼Œå¦‚ httpï¼Œhttpsï¼Œhttp ä¸ https
      - http
      - https
    environment: release # å‘å¸ƒç¯å¢ƒ. ç›®å‰æ”¯æŒä¸‰ç§å‘å¸ƒç¯å¢ƒ: testï¼ˆæµ‹è¯•ï¼‰, prepubï¼ˆé¢„å‘å¸ƒï¼‰ ä¸ releaseï¼ˆå‘å¸ƒï¼‰.
