org: jason
app: customer-feedback-form
stage: dev
component: express
name: customer-feedback-form-api

inputs:
  src:
    src: ./
    exclude:
      - .env
  functionName: ${name}
  region: ${env:REGION}
  runtime: Nodejs10.15
  functionConf:
    timeout: 30
    vpcConfig:
      vpcId: ${output:${stage}:${app}:customer-feedback-form-vpc.vpcId}
      subnetId: ${output:${stage}:${app}:customer-feedback-form-vpc.subnetId}
    environment:
      variables:
        PG_CONNECT_STRING: ${output:${stage}:${app}:customer-feedback-form-db.private.connectionString}
  apigatewayConf:
    enableCORS: true
    protocols:
      - http
      - https
