# æ¬¢è¿ä½¿ç”¨ âš¡ï¸serverlessâš¡ï¸ ç»„ä»¶
#
# serverlessç»„ä»¶æ˜¯åŸºäºå…·ä½“ä½¿ç”¨åœºæ™¯(Express, é™æ€ç½‘ç«™ç­‰)æä¾›çš„å®šåˆ¶äº‘èµ„æºç¼–æ’å’Œç»„ç»‡çš„è§£å†³æ–¹æ¡ˆã€‚
# è¿™æ˜¯serverlessçš„ä¸»è¦é…ç½®æ–‡ä»¶ï¼ŒåŒ…å«äº†ä¸€äº›ä½¿ç”¨ç¤ºä¾‹ä»¥åŠæ³¨é‡Šè¯´æ˜ã€‚
# æ‚¨åªéœ€å‡ è¡Œé…ç½®æè¿°ï¼Œå³å¯è¿›è¡Œäº‘å‡½æ•°ã€API ç½‘å…³ã€COSã€DB ç­‰
# Serverless èµ„æºè¿›è¡Œå¿«é€Ÿåˆ›å»ºã€éƒ¨ç½²å’Œä¿®æ”¹ã€‚
#
# æœ‰å…³å®Œæ•´çš„é…ç½®é€‰é¡¹ï¼Œè¯·æ£€æŸ¥æ–‡æ¡£ï¼š
# https://cloud.tencent.com/document/product/1154/51080
#
# ğŸ‘©â€ğŸ’» Happy Coding ğŸ‘¨â€ğŸ’»

#åº”ç”¨ä¿¡æ¯
app: scf-starter

#ç»„ä»¶ä¿¡æ¯
component: scf # (å¿…å¡«) å¼•ç”¨ component çš„åç§°ï¼Œå½“å‰ç”¨åˆ°çš„æ˜¯ tencent-scf ç»„ä»¶
name: scfdemo # (å¿…å¡«) åˆ›å»ºçš„å®ä¾‹åç§°ï¼Œè¯·ä¿®æ”¹æˆæ‚¨çš„å®ä¾‹åç§°

# ##scf ç»„ä»¶é…ç½®##
# æ›´å¤šå†…å®¹è¯·æŸ¥çœ‹: https://github.com/serverless-components/tencent-scf/blob/master/docs/configure.md
#ç»„ä»¶å‚æ•°
inputs:
  src: ./ #ä»£ç è·¯å¾„
  handler: index.main_handler # å‡½æ•°æ–¹æ³•åç§°ã€æ–‡ä»¶åç§°.å‡½æ•°åç§°ã€‘ã€‚åç§°è¦æ±‚å­—æ¯å¼€å§‹å’Œç»“å°¾ï¼Œå…è®¸ä½¿ç”¨æ•°å­—ã€ä¸‹åˆ’çº¿(_)å’Œè¿æ¥ç¬¦(-)ï¼Œ2-60 ä¸ªå­—ç¬¦ã€‚
  runtime: Nodejs10.15 # è¿è¡Œç¯å¢ƒã€‚[Nodejs10.15, Nodejs12.16]
  region: ap-guangzhou # éƒ¨ç½²ç›®æ ‡åœ°åŒºã€‚ æ›´å¤šå‚è€ƒ https://cloud.tencent.com/document/api/583/17238#.E5.9C.B0.E5.9F.9F.E5.88.97.E8.A1.A8
  events: # è§¦å‘å™¨
    - apigw: # ç½‘å…³è§¦å‘å™¨
        parameters:
          endpoints:
            - path: /
              method: GET
